# -*- coding: utf-8 -*-
"""Copy of Theses_Projject_New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBwBOqonqAfgqEd3fzBVcTHrkToLjcmT
"""

9!pip install transformers
!pip install sentencepiece
!pip install nltk
!pip install seaborn

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

"""**Download NLP Resources**"""

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')

"""**Dataset Uploading**"""

df = pd.read_csv('/content/sample_data/stockerbot-export1.csv')

from google.colab import drive
drive.mount('/content/drive')

"""To view Dataset"""

df.head()

"""Checking of Datastructure"""

df.info()

"""Checking of columns"""

df.columns

"""**STEP 6 — Check Missing Values ..**


 As missing texts causes most errors in NLP models


"""

df.isnull().sum()

df = df[['text']]

df.head()

"""STEP 8 — Remove Missing Tweets"""

df.dropna(inplace=True)

print(df.shape)

"""STEP 9 — Create Copy of Original Text"""

df['original_text'] = df['text']

"""STEP 10 — Text Cleaning Function"""

def clean_text(text):

    text = str(text)

    # remove URLs
    text = re.sub(r"http\S+", "", text)

    # remove mentions
    text = re.sub(r"@\w+", "", text)

    # remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # lowercase
    text = text.lower()

    # remove extra spaces
    text = text.strip()

    return text

"""STEP 11 — Apply Cleaning"""

df['clean_text'] = df['text'].apply(clean_text)

df[['text','clean_text']].head(10)

"""STEP 12 — Remove Stopwords

words like the, is, for, at, and

Create stopword function
"""

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):

    words = word_tokenize(text)

    filtered_words = [
        word for word in words
        if word not in stop_words
    ]

    return " ".join(filtered_words)

"""Apply stopword removal"""

import nltk
nltk.download('punkt_tab')

df['processed_text'] = (
    df['clean_text']
    .apply(remove_stopwords)
)

"""STEP 13 — Check Final Processed Text"""

df[
    ['original_text',
     'processed_text']
].head(10)

"""STEP 14 — Remove Empty Tweets"""

df = df[
    df['processed_text'].str.strip() != ''
]

print(df.shape)

"""STEP 15 — Check Random Samples"""

df[
    ['original_text',
     'processed_text']
].sample(20)

"""STEP 16 — Limit Tweet Length"""

df['processed_text'] = (
    df['processed_text']
    .str[:512]
)

"""STEP 17 — Save Clean Dataset"""

df.to_csv(
    "cleaned_financial_tweets.csv",
    index=False
)

"""Model Working

STEP 18 — Load FinBERT
"""

from transformers import pipeline

finbert = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert"
)

"""STEP 19 — Run FinBERT Sentiment Analysis"""

texts = df['processed_text'].tolist()

finbert_results = finbert(
    texts,
    batch_size=32
)

{
'label': 'positive',
'score': 0.97
}

"""STEP 20 — Save FinBERT Results

here we will use batch processing
"""

df['finbert_sentiment'] = [
    x['label']
    for x in finbert_results
]

df['finbert_score'] = [
    x['score']
    for x in finbert_results
]

"""Checking results"""

df[
    ['processed_text',
     'finbert_sentiment',
     'finbert_score']
].head(10)

"""STEP 21 — FinBERT Distribution"""

df['finbert_sentiment'].value_counts()

plt.figure(figsize=(8,5))

sns.countplot(
    x='finbert_sentiment',
    data=df
)

plt.title(
    'FinBERT Sentiment Distribution'
)

plt.show()

"""Load RoBERTa"""

roberta = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-roberta-base-sentiment-latest"
)

"""STEP 23 — Run RoBERTa"""

roberta_results = roberta(
    texts,
    batch_size=32
)

roberta_results[:10]

[
 {'label': 'positive', 'score': 0.94},
 {'label': 'neutral', 'score': 0.81},
 {'label': 'negative', 'score': 0.88}
]

"""STEP 24 — Sentiment columns"""

df['roberta_sentiment'] = [
    x['label']
    for x in roberta_results
]

df['roberta_score'] = [
    x['score']
    for x in roberta_results
]

df['roberta_sentiment'].value_counts()

plt.figure(figsize=(8,5))

sns.countplot(
    x='roberta_sentiment',
    data=df
)

plt.title(
    'RoBERTa Sentiment Distribution'
)

plt.show()



"""STEP 27 — Load VADER"""

from nltk.sentiment.vader import (
    SentimentIntensityAnalyzer
)

sia = SentimentIntensityAnalyzer()

"""STEP 28 — Create VADER Function"""

def vader_sentiment(text):

    score = (
        sia.polarity_scores(text)
        ['compound']
    )

    if score >= 0.05:
        return 'positive'

    elif score <= -0.05:
        return 'negative'

    else:
        return 'neutral'

"""STEP 29 — Apply VADER"""

df['vader_sentiment'] = (
    df['processed_text']
    .apply(vader_sentiment)
)

"""STEP 30 — VADER Distribution"""

df['vader_sentiment'].value_counts()

plt.figure(figsize=(8,5))

sns.countplot(
    x='vader_sentiment',
    data=df
)

plt.title(
    'VADER Sentiment Distribution'
)

plt.show()

"""FinancialBERT"""

from transformers import pipeline

financialbert = pipeline(
"sentiment-analysis",
model="ahmedrachid/FinancialBERT-Sentiment-Analysis"
)

texts = df['processed_text'].tolist()

"""STEP 37 — Run FinancialBERT"""

financialbert_results = financialbert(
    texts,
    batch_size=32
)

"""Prepare_text"""

texts = df['processed_text'].tolist()

[
 {'label': 'positive', 'score': 0.97},
 {'label': 'neutral', 'score': 0.88},
 {'label': 'negative', 'score': 0.93}
]

"""STEP 38 — Check Output Format FIRST"""

financialbert_results[:10]

"""Save FinancialBERT Results"""

df['financialbert_sentiment'] = [

    x['label']

    for x in financialbert_results
]

df['financialbert_score'] = [

    x['score']

    for x in financialbert_results
]

"""STEP 40 — Check Results"""

df[
[
'processed_text',
'financialbert_sentiment',
'financialbert_score'
]
].head(10)

"""STEP 41 — Check Sentiment Distribution"""

df[
'financialbert_sentiment'
].value_counts()

"""STEP 42 — Create Graph"""

plt.figure(figsize=(8,5))

sns.countplot(
    x='financialbert_sentiment',
    data=df
)

plt.title(
'FinancialBERT Sentiment Distribution'
)

plt.show()



df.columns

"""STEP 31 — Compare All Models
We compare:

FinBERT
RoBERTa
VADER
FinancialBERT
"""

comparison = pd.DataFrame({

'FinBERT':
df['finbert_sentiment']
.value_counts(),

'RoBERTa':
df['roberta_sentiment']
.value_counts(),

'VADER':
df['vader_sentiment']
.value_counts(),

'FinancialBERT':
df['financialbert_sentiment']
.value_counts()

})

comparison

"""STEP 44 — Comparison Graph"""

comparison.plot(
    kind='bar',
    figsize=(12,6)
)

plt.title(
'Sentiment Comparison Across NLP Models'
)

plt.ylabel(
'Number of Tweets'
)

plt.show()

comparison_percentage = (
    comparison.div(comparison.sum(axis=0), axis=1)
    * 100
)

comparison_percentage.round(2)

"""STEP 45 — Create Comparison Table"""

comparison = pd.DataFrame({

'FinBERT':
df['finbert_sentiment']
.value_counts(),

'RoBERTa':
df['roberta_sentiment']
.value_counts(),

'VADER':
df['vader_sentiment']
.value_counts(),

'FinancialBERT':
df['financialbert_sentiment']
.value_counts()

})

comparison

"""STEP 46 — Convert to Percentages"""

comparison_percentage = (

comparison.div(
comparison.sum(axis=0),
axis=1

) * 100

)

comparison_percentage.round(2)

"""STEP 47"""

comparison_percentage.T.plot(

kind='bar',
figsize=(12,6)

)

plt.title(
'Percentage Distribution Across NLP Models'
)

plt.ylabel(
'Percentage (%)'
)

plt.xticks(rotation=0)

plt.show()

"""STEP 48 — Find Model Disagreement"""

finbert_roberta_disagreement = df[

df['finbert_sentiment']

!=

df['roberta_sentiment']

]

len(finbert_roberta_disagreement)

"""View examples"""

finbert_roberta_disagreement[
[
'original_text',
'processed_text',
'finbert_sentiment',
'roberta_sentiment'
]
].head(20)

"""STEP 49 — Compare FinBERT vs VADER"""

finbert_vader_disagreement = df[

df['finbert_sentiment']

!=

df['vader_sentiment']

]

len(finbert_vader_disagreement)

finbert_vader_disagreement[
[
'original_text',
'processed_text',
'finbert_sentiment',
'vader_sentiment'
]
].head(20)

"""STEP 50 — Compare FinBERT vs FinancialBERT"""

finbert_financialbert_disagreement = df[

df['finbert_sentiment']

!=

df['financialbert_sentiment']

]

len(finbert_financialbert_disagreement)

finbert_financialbert_disagreement[
[
'original_text',
'processed_text',
'finbert_sentiment',
'financialbert_sentiment'
]
].head(20)

"""STEP 51 — Calculate Agreement Rate"""

agreement = (

df['finbert_sentiment']

==

df['roberta_sentiment']

).mean() * 100

print(
f"Agreement Rate: {agreement:.2f}%"
)

"""FinBERT vs VADER"""

agreement_vader = (

df['finbert_sentiment']

==

df['vader_sentiment']

).mean() * 100

print(
f"Agreement Rate: {agreement_vader:.2f}%"
)

"""FinBERT vs FinancialBERT"""

agreement_financialbert = (

df['finbert_sentiment']

==

df['financialbert_sentiment']

).mean() * 100

print(
f"Agreement Rate: {agreement_financialbert:.2f}%"
)

"""Evaluation

STEP 52 — Create Ground Truth Labels
"""

evaluation_df = df.sample(
    300,
    random_state=42
).copy()

evaluation_df = evaluation_df[
[
'original_text',
'finbert_sentiment',
'roberta_sentiment',
'vader_sentiment',
'financialbert_sentiment'
]
]

evaluation_df.reset_index(
    drop=True,
    inplace=True
)

evaluation_df.head(20)

"""STEP 53 — Add Manual Label Column"""

evaluation_df[
'true_label'
] = ''

"""STEP 54 — Export for Manual Labeling"""

evaluation_df.to_csv(
    "manual_labeling_1.csv",
    index=False
)

import pandas as pd

df = pd.read_csv('/content/sample_data/thesis_after_comments.csv')

evaluation_df =  pd.read_csv('/content/sample_data/thesis_after_comments.csv')

"""STEP 58 — Check Labels"""

evaluation_df.head(50)

evaluation_df['true_label'].value_counts()

evaluation_df[['original_text','true_label']].head(20)

"""STEP 57 — Import Evaluation Libraries"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

"""Evaluate All Models Together"""

results = []

models = {

    'FinBERT': evaluation_df['finbert_sentiment'],

    'RoBERTa': evaluation_df['roberta_sentiment'],

    'VADER': evaluation_df['vader_sentiment'],

    'FinancialBERT': evaluation_df['financialbert_sentiment']

}

for model_name, prediction in models.items():

    accuracy = accuracy_score(
        evaluation_df['true_label'],
        prediction
    )

    precision = precision_score(
        evaluation_df['true_label'],
        prediction,
        average='weighted'
    )

    recall = recall_score(
        evaluation_df['true_label'],
        prediction,
        average='weighted'
    )

    f1 = f1_score(
        evaluation_df['true_label'],
        prediction,
        average='weighted'
    )

    results.append([
        model_name,
        accuracy,
        precision,
        recall,
        f1
    ])

"""Create Results Table"""

results_df = pd.DataFrame(

results,

columns=[
    'Model',
    'Accuracy',
    'Precision',
    'Recall',
    'F1 Score'
]

)

results_df

"""Performance Graph"""

results_df.set_index(
    'Model'
).plot(
    kind='bar',
    figsize=(12,6)
)

plt.title(
    'Model Performance Comparison'
)

plt.ylabel(
    'Score'
)

plt.xticks(rotation=0)

plt.show()

"""Confusion Matrix for FinBERT"""

cm_finbert = confusion_matrix(

    evaluation_df['true_label'],

    evaluation_df['finbert_sentiment'],

    labels=[
        'negative',
        'neutral',
        'positive'
    ]

)

plt.figure(figsize=(6,5))

sns.heatmap(

    cm_finbert,

    annot=True,

    fmt='d',

    cmap='Blues',

    xticklabels=[
        'negative',
        'neutral',
        'positive'
    ],

    yticklabels=[
        'negative',
        'neutral',
        'positive'
    ]

)

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('FinBERT Confusion Matrix')

plt.show()

results_df



"""Model Performance Comparison"""

plt.figure(figsize=(10,6))

results_df.set_index('Model').plot(
    kind='bar'
)

plt.title(
    'Performance Comparison of Sentiment Analysis Models'
)

plt.ylabel('Score')

plt.xticks(rotation=0)

plt.legend(
    loc='lower right'
)

plt.show()

"""Accuracy Comparison"""

plt.figure(figsize=(8,5))

sns.barplot(
    x='Model',
    y='Accuracy',
    data=results_df
)

plt.title(
    'Accuracy Comparison Across Models'
)

plt.ylim(0,1)

plt.show()

"""F1 Score Comparison"""

plt.figure(figsize=(8,5))

sns.barplot(
    x='Model',
    y='F1 Score',
    data=results_df
)

plt.title(
    'F1 Score Comparison Across Models'
)

plt.ylim(0,1)

plt.show()

"""Confusion Matrix for Every Model"""

cm = confusion_matrix(
    evaluation_df['true_label'],
    evaluation_df['finbert_sentiment'],
    labels=['negative','neutral','positive']
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['negative','neutral','positive'],
    yticklabels=['negative','neutral','positive']
)

plt.title('FinBERT Confusion Matrix')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.show()

cm = confusion_matrix(
    evaluation_df['true_label'],
    evaluation_df['roberta_sentiment'],
    labels=['negative','neutral','positive']
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['negative','neutral','positive'],
    yticklabels=['negative','neutral','positive']
)

plt.title('RoBERTa Confusion Matrix')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.show()

cm = confusion_matrix(
    evaluation_df['true_label'],
    evaluation_df['vader_sentiment'],
    labels=['negative','neutral','positive']
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['negative','neutral','positive'],
    yticklabels=['negative','neutral','positive']
)

plt.title('VADER Confusion Matrix')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.show()

cm = confusion_matrix(
    evaluation_df['true_label'],
    evaluation_df['financialbert_sentiment'],
    labels=['negative','neutral','positive']
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['negative','neutral','positive'],
    yticklabels=['negative','neutral','positive']
)

plt.title('FinancialBERT Confusion Matrix')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.show()

"""Combined confusion matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

models = {
    'FinBERT': 'finbert_sentiment',
    'RoBERTa': 'roberta_sentiment',
    'VADER': 'vader_sentiment',
    'FinancialBERT': 'financialbert_sentiment'
}

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

axes = axes.flatten()

for ax, (model_name, column) in zip(axes, models.items()):

    cm = confusion_matrix(
        evaluation_df['true_label'],
        evaluation_df[column],
        labels=['negative', 'neutral', 'positive']
    )

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=['negative', 'neutral', 'positive'],
        yticklabels=['negative', 'neutral', 'positive'],
        ax=ax
    )

    ax.set_title(f'{model_name}')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')

plt.suptitle(
    'Confusion Matrix Comparison Across NLP Models',
    fontsize=16,
    y=1.02
)

plt.tight_layout()

plt.show()

"""Agreement Rate Comparison"""

agreement_results = pd.DataFrame({

'Comparison':[
'FinBERT vs RoBERTa',
'FinBERT vs VADER',
'FinBERT vs FinancialBERT'
],

'Agreement Rate':[
81.07,
56.95,
74.16
]

})

plt.figure(figsize=(8,5))

sns.barplot(
    x='Comparison',
    y='Agreement Rate',
    data=agreement_results
)

plt.title(
    'Agreement Rates Between Models'
)

plt.ylabel('Agreement (%)')

plt.show()

"""classification report

FinancialBERT (Best Model)
"""

from sklearn.metrics import classification_report

print("FinancialBERT Classification Report\n")

print(
    classification_report(
        evaluation_df['true_label'],
        evaluation_df['financialbert_sentiment']
    )
)

"""FinBERT"""

print("FinBERT Classification Report\n")

print(
    classification_report(
        evaluation_df['true_label'],
        evaluation_df['finbert_sentiment']
    )
)

"""
RoBERTa"""

print("RoBERTa Classification Report\n")

print(
    classification_report(
        evaluation_df['true_label'],
        evaluation_df['roberta_sentiment']
    )
)

"""VADER"""

print("VADER Classification Report\n")

print(
    classification_report(
        evaluation_df['true_label'],
        evaluation_df['vader_sentiment']
    )
)

"""Generate All Classification Reports Together"""

models = {
    'FinBERT': 'finbert_sentiment',
    'RoBERTa': 'roberta_sentiment',
    'VADER': 'vader_sentiment',
    'FinancialBERT': 'financialbert_sentiment'
}

for model_name, column in models.items():

    print("\n" + "="*60)
    print(model_name)
    print("="*60)

    print(
        classification_report(
            evaluation_df['true_label'],
            evaluation_df[column]
        )
    )

"""| Model         | Accuracy | Precision | Recall | F1 Score |
| ------------- | -------: | --------: | -----: | -------: |
| FinancialBERT |    81.67 |     82.87 |  81.67 |    80.55 |
| FinBERT       |    77.00 |     78.38 |  77.00 |    74.31 |
| RoBERTa       |    69.33 |     69.74 |  69.33 |    65.32 |
| VADER         |    56.00 |     65.45 |  56.00 |    58.20 |

Phase 7  - Visualizations

Figure 1 — Sentiment Distribution Comparison  -- already did

Figure 2 — Agreement Rate Comparison - already did
Shows model consistency.
"""

agreement_results = pd.DataFrame({

'Comparison':[
'FinBERT vs RoBERTa',
'FinBERT vs FinancialBERT',
'FinBERT vs VADER'
],

'Agreement Rate':[
81.07,
74.16,
56.95
]

})

plt.figure(figsize=(8,5))

sns.barplot(
    x='Comparison',
    y='Agreement Rate',
    data=agreement_results
)

plt.title(
    'Agreement Rates Between Models'
)

plt.ylabel('Agreement (%)')

plt.show()

"""Figure 3 — Accuracy Comparison"""

plt.figure(figsize=(8,5))

sns.barplot(
    x='Model',
    y='Accuracy',
    data=results_df
)

plt.title(
    'Accuracy Comparison Across Models'
)

plt.ylim(0,1)

plt.show()

"""Figure 4 — F1 Score Comparison"""

plt.figure(figsize=(8,5))

sns.barplot(
    x='Model',
    y='F1 Score',
    data=results_df
)

plt.title(
    'F1 Score Comparison Across Models'
)

plt.ylim(0,1)

plt.show()

"""Figure 5 — Combined Confusion Matrix  - already did

Figure 6 — Performance Comparison Dashboard
"""

plt.figure(figsize=(12,6))

results_df.set_index('Model').plot(
    kind='bar'
)

plt.title(
    'Performance Comparison of Sentiment Analysis Models'
)

plt.ylabel('Score')

plt.xticks(rotation=0)

plt.show()

"""Figure 7 — Model Ranking"""

ranking_df = pd.DataFrame({

'Model':[
'FinancialBERT',
'FinBERT',
'RoBERTa',
'VADER'
],

'Accuracy':[
81.67,
77.00,
69.33,
56.00
]

})

plt.figure(figsize=(8,5))

sns.barplot(
    x='Model',
    y='Accuracy',
    data=ranking_df
)

plt.title(
    'Final Ranking of NLP Models'
)

plt.ylabel('Accuracy (%)')

plt.show()

""" Results Table"""

results_df

results_df.to_csv(
    'final_results.csv',
    index=False
)